[package]
name = "lumbergh"
version = "0.0.1"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[dependencies]
error-chain = "^0.9.0"
libc = { git = "https://github.com/rust-lang/libc.git", branch = "master" }
nix = "^0.7.0"
